create table cats (
	id INT,
	Cat_name VARCHAR(50),
	Cat_breed VARCHAR(9),
	Owner VARCHAR(50),
	gender VARCHAR(50),
	Stay DATE
);
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (1, 'Hastings', 'tuxedo', 'hwhitton0@clickbank.net', 'Male', '1/10/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (2, 'Maribeth', 'blue hair', 'mpinchen1@harvard.edu', 'Female', '6/6/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (3, 'Anestassia', 'tabby', 'alarby2@indiatimes.com', 'Female', '1/9/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (4, 'Inigo', 'siamese', 'ipester3@amazonaws.com', 'Male', '8/21/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (5, 'Patric', 'tuxedo', 'pwillbourne4@blogs.com', 'Male', '3/7/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (6, 'Lizbeth', 'calico', 'llobb5@cloudflare.com', 'Female', '4/18/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (7, 'Roddie', 'tuxedo', 'rrabjohn6@nbcnews.com', 'Male', '9/3/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (8, 'Kirstyn', 'blue hair', 'klongland7@businessweek.com', 'Female', '11/4/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (9, 'Ariel', 'blue hair', 'ahancill8@biglobe.ne.jp', 'Female', '8/22/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (10, 'Thorn', 'siamese', 'tshewsmith9@feedburner.com', 'Male', '5/21/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (11, 'Bathsheba', 'tabby', 'bmerrella@wix.com', 'Female', '12/31/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (12, 'Kenna', 'persian', 'kgommeb@addtoany.com', 'Female', '5/19/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (13, 'Tiebold', 'blue hair', 'tbellenyc@wiley.com', 'Male', '8/5/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (14, 'Raimundo', 'calico', 'ritzigd@time.com', 'Non-binary', '4/8/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (15, 'Betsey', 'blue hair', 'bandore@t.co', 'Female', '12/6/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (16, 'Brandie', 'calico', 'bsisslandf@adobe.com', 'Female', '11/22/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (17, 'Mitzi', 'tuxedo', 'mhuertasg@ameblo.jp', 'Female', '7/8/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (18, 'Philis', 'blue hair', 'pburchallh@marketwatch.com', 'Female', '4/28/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (19, 'Ephrem', 'calico', 'ebriersi@google.com.au', 'Male', '9/16/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (20, 'Edvard', 'tuxedo', 'emartusewiczj@buzzfeed.com', 'Male', '9/12/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (21, 'Langsdon', 'tuxedo', 'lmolyneauxk@va.gov', 'Male', '2/8/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (22, 'Mendel', 'calico', 'mboasl@europa.eu', 'Genderfluid', '5/20/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (23, 'Sampson', 'siamese', 'skonradm@microsoft.com', 'Male', '3/15/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (24, 'Roslyn', 'persian', 'rsimmonettn@fema.gov', 'Genderfluid', '10/1/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (25, 'Carmelia', 'blue hair', 'cphilliphso@paginegialle.it', 'Female', '11/20/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (26, 'Cullen', 'persian', 'cbartelsellisp@prnewswire.com', 'Male', '2/8/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (27, 'Maiga', 'tuxedo', 'mbattesonq@twitpic.com', 'Female', '3/7/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (28, 'Harry', 'siamese', 'hwrayr@i2i.jp', 'Male', '8/31/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (29, 'Sig', 'calico', 'srallss@ihg.com', 'Male', '7/30/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (30, 'Odetta', 'persian', 'opoznant@imgur.com', 'Female', '9/11/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (31, 'Regina', 'siamese', 'rschreineru@fc2.com', 'Female', '5/23/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (32, 'Garrik', 'persian', 'gdriv@mediafire.com', 'Male', '5/24/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (33, 'Lorrayne', 'tabby', 'ltuttlew@posterous.com', 'Female', '8/25/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (34, 'Lilias', 'tabby', 'lvairowx@businessweek.com', 'Female', '8/3/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (35, 'Rosalinde', 'tabby', 'rrenyardy@foxnews.com', 'Female', '1/11/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (36, 'Tim', 'persian', 'tgoodrichz@bing.com', 'Female', '12/20/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (37, 'Bo', 'siamese', 'bbruinemann10@who.int', 'Male', '11/27/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (38, 'Ermin', 'blue hair', 'eraikes11@answers.com', 'Male', '7/14/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (39, 'Barnett', 'tabby', 'bescoffier12@soundcloud.com', 'Male', '2/17/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (40, 'Gregory', 'blue hair', 'gupshall13@foxnews.com', 'Genderfluid', '12/22/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (41, 'Mabelle', 'tuxedo', 'mpurdey14@smugmug.com', 'Female', '3/16/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (42, 'Butch', 'calico', 'bshakespeare15@aol.com', 'Male', '1/10/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (43, 'Petey', 'blue hair', 'poverland16@is.gd', 'Male', '5/24/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (44, 'Teressa', 'tabby', 'tbrachell17@uiuc.edu', 'Female', '11/9/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (45, 'Demetria', 'persian', 'dmccullock18@cmu.edu', 'Female', '5/11/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (46, 'Bevon', 'tuxedo', 'bimeson19@photobucket.com', 'Male', '4/12/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (47, 'Ian', 'tabby', 'igladbeck1a@moonfruit.com', 'Male', '5/20/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (48, 'Dalli', 'tuxedo', 'dgreensted1b@cam.ac.uk', 'Male', '8/1/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (49, 'Vivi', 'blue hair', 'vtumulty1c@sciencedirect.com', 'Female', '8/18/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (50, 'Jameson', 'siamese', 'jtyrone1d@cpanel.net', 'Male', '10/19/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (51, 'Vally', 'persian', 'vsucre1e@cbslocal.com', 'Female', '1/23/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (52, 'Dido', 'siamese', 'dframmingham1f@sakura.ne.jp', 'Female', '7/15/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (53, 'Maynord', 'siamese', 'mcaldaro1g@cnbc.com', 'Male', '5/20/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (54, 'Hercules', 'tuxedo', 'htunuy1h@timesonline.co.uk', 'Male', '2/22/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (55, 'Eustace', 'calico', 'ehartness1i@nih.gov', 'Male', '6/28/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (56, 'Abbot', 'persian', 'acluett1j@blogs.com', 'Male', '1/28/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (57, 'Luise', 'tabby', 'ldelgadillo1k@opera.com', 'Genderqueer', '3/5/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (58, 'Devonna', 'tabby', 'dkleinhaus1l@microsoft.com', 'Female', '8/12/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (59, 'Meade', 'blue hair', 'mmorstatt1m@cbsnews.com', 'Male', '5/17/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (60, 'Roxine', 'persian', 'rcaldicot1n@blogger.com', 'Female', '9/11/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (61, 'Cathie', 'tuxedo', 'ctschirasche1o@tripod.com', 'Female', '8/27/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (62, 'Stephana', 'calico', 'slaughrey1p@independent.co.uk', 'Female', '6/11/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (63, 'Doroteya', 'tuxedo', 'dcamellini1q@blogger.com', 'Female', '2/14/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (64, 'Ennis', 'calico', 'egrise1r@indiatimes.com', 'Male', '10/17/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (65, 'Loy', 'tabby', 'lperell1s@example.com', 'Genderfluid', '6/19/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (66, 'Abby', 'tuxedo', 'aorteau1t@marketwatch.com', 'Male', '4/22/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (67, 'Bree', 'blue hair', 'bsenter1u@flavors.me', 'Female', '6/9/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (68, 'Melva', 'calico', 'mpeckham1v@wisc.edu', 'Female', '2/6/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (69, 'Alida', 'persian', 'agendricke1w@newsvine.com', 'Female', '9/10/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (70, 'Abran', 'calico', 'athunnercliffe1x@google.nl', 'Male', '7/22/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (71, 'Catherina', 'tabby', 'cwilcott1y@goodreads.com', 'Female', '6/15/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (72, 'Bram', 'blue hair', 'bsmelley1z@forbes.com', 'Male', '5/14/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (73, 'Tommie', 'siamese', 'tlinklet20@amazon.com', 'Female', '10/30/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (74, 'Andreas', 'blue hair', 'amonget21@people.com.cn', 'Male', '2/25/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (75, 'Dal', 'siamese', 'droggerone22@nymag.com', 'Male', '5/8/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (76, 'Ross', 'siamese', 'rmcmenamy23@posterous.com', 'Male', '2/15/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (77, 'Katey', 'tabby', 'kallner24@blogger.com', 'Female', '10/7/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (78, 'Tresa', 'tuxedo', 'tlorentzen25@google.de', 'Female', '7/7/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (79, 'Harrie', 'blue hair', 'hstanyer26@prnewswire.com', 'Female', '8/14/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (80, 'Titus', 'tabby', 'tharms27@smh.com.au', 'Male', '6/17/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (81, 'Hunt', 'persian', 'hauckland28@nih.gov', 'Genderqueer', '5/21/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (82, 'Othello', 'siamese', 'owrassell29@biglobe.ne.jp', 'Male', '12/29/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (83, 'Katha', 'persian', 'krosiello2a@360.cn', 'Female', '1/9/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (84, 'Timmie', 'siamese', 'tjordi2b@prnewswire.com', 'Male', '2/13/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (85, 'Evered', 'blue hair', 'ecortin2c@tumblr.com', 'Male', '9/8/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (86, 'Elsy', 'tabby', 'elockwood2d@mayoclinic.com', 'Female', '7/9/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (87, 'Luz', 'tabby', 'lpraton2e@narod.ru', 'Female', '8/15/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (88, 'Colas', 'tuxedo', 'crigler2f@comcast.net', 'Male', '11/23/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (89, 'Rahal', 'persian', 'rprothero2g@bandcamp.com', 'Female', '3/9/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (90, 'Raffarty', 'persian', 'rmutch2h@nih.gov', 'Bigender', '10/29/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (91, 'Patrizio', 'calico', 'pjaher2i@home.pl', 'Male', '3/28/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (92, 'Welbie', 'tuxedo', 'whurdidge2j@time.com', 'Male', '1/4/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (93, 'Elfie', 'blue hair', 'efarlane2k@cdbaby.com', 'Female', '7/3/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (94, 'Alonso', 'tabby', 'alevens2l@prlog.org', 'Male', '3/10/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (95, 'Bridie', 'tabby', 'bkestle2m@pagesperso-orange.fr', 'Female', '6/24/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (96, 'Granger', 'blue hair', 'gledgley2n@list-manage.com', 'Male', '5/25/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (97, 'Ange', 'siamese', 'ahearst2o@networksolutions.com', 'Female', '11/1/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (98, 'Shaylah', 'blue hair', 'sbaseggio2p@stanford.edu', 'Female', '1/3/2024');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (99, 'Rhonda', 'tuxedo', 'rdavidovici2q@cornell.edu', 'Female', '12/8/2023');
insert into cats (id, Cat_name, Cat_breed, Owner, gender, Stay) values (100, 'Thane', 'calico', 'tsweeny2r@blinklist.com', 'Male', '10/28/2023');
